---
- name: Install packages required by ansible
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: install libselinux python support
      package:
        name: libselinux-python

    - name: install pip
      package:
        name: python-pip

    - name: install requests
      package:
        name: python-requests

    - name: install virtualenv
      package:
        name: python-virtualenv
