#! /bin/bash
#
# This script builds the Docker images that compose the testing environment and
# the ansible-tester image.

set -o errexit -o nounset -o pipefail

export CA_NAME DOMAIN


main()
{
  local execName
  execName=$(resolve_exec "$0")

  local baseDir
  baseDir=$(dirname "$execName")

  # shellcheck disable=SC1090
  . "$baseDir"/config.inc

  mk_tls "$baseDir"
  "$baseDir"/env/build "$baseDir"/config.inc
  "$baseDir"/ansible-tester/build "$baseDir"/config.inc
}


mk_tls()
{
  local baseDir="$1"

  local sslTmpl="$baseDir"/openssl.tmpl

  local workDir="$baseDir"/.tls
  local controlDir="$workDir"/control
  local envDir="$workDir"/env

  local buildSslCnf="$workDir"/openssl.cnf
  if [[ "$sslTmpl" -nt "$buildSslCnf" ]]
  then
    local tmpSslCnf
    tmpSslCnf=$(mktemp)

    sed 's|_CA_DIR_|'"$controlDir"'/CA|' "$sslTmpl" > "$tmpSslCnf"

    if ! diff --brief "$tmpSslCnf" "$buildSslCnf" &> /dev/null
    then
      rm --force --recursive "$workDir"
      mkdir --parents "$workDir"
      mv "$tmpSslCnf" "$buildSslCnf"
    else
      rm --force "$tmpSslCnf"
      touch "$buildSslCnf"
    fi
  fi

  prep_ca "$baseDir" "$buildSslCnf" "$controlDir"
  prep_tls "$buildSslCnf" "$envDir"

  prep_env "$workDir" "$baseDir"/env/.tls
  prep_control "$workDir" "$baseDir"/ansible-tester/.tls
}


prep_ca()
{
  local baseDir="$1"
  local buildSslCnf="$2"
  local controlDir="$3"

  local controlSslCnf="$controlDir"/openssl.cnf
  if [[ "$baseDir"/openssl.tmpl -nt "$controlSslCnf" ]]
  then
    rm --force --recursive "$controlDir"
    mkdir --parents "$controlDir"
    sed 's|_CA_DIR_|/etc/pki/CA|' "$baseDir"/openssl.tmpl > "$controlSslCnf"
    printf 'Updated openssl.cnf for CA\n'
  fi

  local caDir="$controlDir"/CA
  mkdir --parents "$caDir"/certs "$caDir"/newcerts "$caDir"/private

  local caKey="$caDir"/private/ca.key
  local caCrt="$caDir"/certs/ca.crt
  local serial="$caDir"/serial
  local index="$caDir"/index.txt
  local idxAttr="$caDir"/index.txt.attr

  if ! [[ -e "$caKey" ]]
  then
    rm --force "$caCrt" "$serial" "$index" "$idxAttr"
    echo 1000 > "$serial"
    touch "$index" "$idxAttr"
    printf 'Reset CA DB\n'

    if ! openssl genpkey -algorithm rsa -out "$caKey" 2> /dev/null
    then
      printf 'Failed to build private key for certificate authority\n' >&2
      return 1
    else
      printf 'Recreated private key for CA\n'
    fi
  fi

  chmod u=r "$caKey"

  if [[ "$caKey" -nt "$caCrt" ]] || ! correct_cn "$caCrt" "$CA_NAME"."$DOMAIN"
  then
    openssl req -new -sha256 -x509 \
      -config "$buildSslCnf" \
      -days 10000 \
      -extensions v3_ca \
      -key "$caKey" \
      -out "$caCrt" \
      -subj /CN="$CA_NAME"."$DOMAIN"

    printf 'Recreated certificate for CA\n'
  fi

  chmod a=r "$caCrt"
}


correct_cn()
{
  local crt="$1"
  local cn="$2"

  local subj
  subj=$(openssl x509 -noout -subject -in "$crt")

  test "$subj" = "subject=CN = $cn"
}


prep_control()
{
  local mainDir="$1"
  local controlDir="$2"

  mkdir --parents "$controlDir"

  local tlsDir="$controlDir"/tls
  mkdir --parents "$tlsDir"

  cp --force --update "$mainDir"/control/openssl.cnf "$tlsDir"/
  cp --force --recursive --update "$mainDir"/control/CA "$controlDir"/
  cp --force --recursive --update "$mainDir"/env/certs "$mainDir"/env/private "$tlsDir"/
}


prep_env()
{
  local mainDir="$1"
  local envDir="$2"

  mkdir --parents "$envDir"
  cp --force --recursive --update "$mainDir"/env/certs "$mainDir"/env/private "$envDir"/
  cp --force --update "$mainDir"/control/CA/certs/ca.crt "$envDir"/certs/root.crt
}


prep_tls()
{
  local sslCnf="$1"
  local envDir="$2"

  if ! [[ -e "$envDir"/private/"$DOMAIN".key ]]
  then
    rm --force --recursive "$envDir"
  fi

  mkdir --parents "$envDir"/certs "$envDir"/private

  mk_tls_pair "$sslCnf" "$envDir" "$DOMAIN"
  mk_tls_pair "$sslCnf" "$envDir" custom
}


mk_tls_pair()
{
  local sslCnf="$1"
  local tlsDir="$2"
  local domain="$3"

  local domainKey="$tlsDir"/private/"$domain".key
  local domainCsr="$tlsDir"/"$domain".csr
  local domainCrt="$tlsDir"/certs/"$domain".crt

  if ! [[ -e "$domainKey" ]]
  then
    rm --force "$domainCsr" "$domainCrt"
    if ! openssl genpkey -algorithm rsa -out "$domainKey" 2> /dev/null
    then
      printf 'Failed to build private TLS key for %s domain\n' "$domain" >&2
      return 1
    else
      printf 'Created private TLS key for %s domain\n' "$domain"
    fi
  fi

  chmod a=r "$domainKey"

  if [[ "$sslCnf" -nt "$domainCsr" ]] || [[ "$domainKey" -nt "$domainCsr" ]]
  then
    openssl req -new -sha256 \
      -config "$sslCnf" -key "$domainKey" -out "$domainCsr" -subj /CN="$domain"

    printf 'Created certificate request for %s domain\n' "$domain"
  fi

  if [[ "$sslCnf" -nt "$domainCrt" ]] || [[ "$domainCsr" -nt "$domainCrt" ]]
  then
    if ! mk_tls_cert "$sslCnf" "$domainCsr" "$domainCrt"
    then
      printf 'Failed to create certificate for %s domain\n' "$domain" >&2
      return 1
    else
      printf 'Created certificate for %s domain\n' "$domain"
    fi
  fi

  chmod a=r "$domainCrt"
}


mk_tls_cert()
{
  local sslCnf="$1"
  local csr="$2"
  local crt="$3"

  openssl ca -batch -notext \
      -config "$sslCnf" \
      -days 10000 \
      -extensions server_cert \
      -in "$csr" \
      -md sha256 \
      -out "$crt" \
    2> /dev/null
}


resolve_exec()
{
  local exe="$1"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    greadlink -f "$exe"
  else
    readlink --canonicalize "$exe"
  fi
}


main "$@"
