#! /bin/bash
#
# This script removes the images built by the build script. Specifically, it
# deletes ansible-tester, all of the images composing env, and the base image
# ansible-support.

set -o errexit -o nounset -o pipefail


resolve_exec()
{
  local exe="$0"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    greadlink -f "$exe"
  else
    readlink --canonicalize "$exe"
  fi
}


main()
{
  local execName
  execName=$(resolve_exec "$0")

  local baseDir
  baseDir=$(dirname "$execName")

  "$baseDir"/ansible-tester/clean
  "$baseDir"/env/clean "$baseDir"/config.inc

  rm --force --recursive "$baseDir"/ansible-tester/.pki "$baseDir"/.working
}


main "$@"
