#! /bin/bash
#
# This script removes the images built by the build script. Specifically, it
# deletes ansible-tester, all of the images composing env, and the base image
# ansible-support.

set -o errexit -o nounset -o pipefail


resolve_exec()
{
  local exe="$0"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    greadlink -f "$exe"
  else
    readlink --canonicalize "$exe"
  fi
}


readonly ExecName=$(resolve_exec "$0")


main()
{
  local baseDir
  baseDir=$(dirname "$ExecName")

  "$baseDir"/ansible-tester/clean
  "$baseDir"/env/clean "$baseDir"/config.inc
}


main "$@"
