#!/bin/bash


show_help()
{
  cat <<EOF

$ExecName

Usage:
  $ExecName [options] <playbook_folder>

test Data Store playbooks

Parameters:
  <playbook_folder>  the path to the root directory for a collection of
                     playbooks

Options:
$(printHelpText)

Summary:
This script runs a playbook with in the testing environment. If no inventory
hosts file is provided, it will use 'hosts-all'. If no playbook is provided, it
will attempt to run the playbook <playbook_folder>/main.yml.
EOF
}

printHelpText(){
  if [[ "$OSTYPE" == "darwin"* ]]
  then
    cat <<EOF
  -I <hosts>      the name of the inventory hosts file to use
  -P <playbook>   the path to the playbook to test relative to <playbook_folder>.

  -h              show help and exit
  -i              after running the playbook, open shell that allows manual
                  inspection of the configuration files, vaults, and logs
  -p              more information will be output and newlines will be expanded
                  in that output.
EOF
  else
    cat <<EOF
  -I, --inventory-hosts <hosts>  the name of the inventory hosts file to use
  -P, --playbook  <playbook>     the path to the playbook to test relative to
                                       <playbook_folder>.

  -h, --help                     show help and exit
  -i, --inspect                  after running the playbook, open shell that
                                 allows manual inspection of the configuration
                                 files, vaults, and logs
  -p, --pretty                   more information will be output and newlines
                                 will be expanded in that output.
EOF
  fi

}


set -o errexit -o nounset -o pipefail


resolve_exec()
{
  local exe="$0"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    greadlink -f "$exe"
  else
    readlink --canonicalize "$exe"
  fi
}


readonly ExecName=$(resolve_exec "$0")
readonly BaseDir=$(dirname "$ExecName")
readonly Cfg="$BaseDir"/config.inc
readonly DefaultHosts=hosts-all
readonly DefaultPlaybook=main.yml

# shellcheck disable=SC1090
. "$Cfg"


main()
{
  local opts
  if ! opts=$(parse_cmd_line "$@")
  then
    show_help >&2
    return 1
  fi

  eval set -- "$opts"

  local doInspect playbookInput pretty
  local hosts="$DefaultHosts"

  while true
  do
    case "$1" in
      -h|--help)
        show_help
        return 0
        ;;
      -I|--inventory-hosts)
        hosts="$2"
        shift 2
        ;;
      -i|--inspect)
        doInspect=true
        shift
        ;;
      -P|--playbook)
        playbookInput="$2"
        shift 2
        ;;
      -p|--pretty)
        pretty=true
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        show_help >&2
        return 1
        ;;
    esac
  done

  if [[ "$#" -lt 1 ]]
  then
    show_help >&2
    return 1
  fi

  local playbook playbooks
  playbooks=$(resolve_playbook_dir "$1")
  playbook=$(resolve_playbook "$playbooks" "${playbookInput-}")

  do_run "${doInspect-}" "${pretty-}" "$playbooks" "$playbook" "$hosts"
}


do_run()
{
  local doInspect="$1"
  local pretty="$2"
  local playbooks="$3"
  local playbook="$4"
  local hosts="$5"

  if "$BaseDir"/env/controller "$Cfg" start
  then
    "$BaseDir"/ansible-tester/run "$doInspect" "$pretty" "$playbooks" "$playbook" "$hosts"
  fi

  "$BaseDir"/env/controller "$Cfg" stop
}


parse_cmd_line()
{
  if [[ "$OSTYPE" == "darwin"* ]]
  then
    getopt hiI:P:p "$*"
  else
    getopt \
      --longoptions help,inspect,inventory-hosts:,playbook:,pretty \
      --options hiI:P:p \
      --name "$ExecName" \
      -- "$@"
  fi
}


resolve_playbook()
{
  local playbooks="$1"
  local playbook="$2"

  : "${playbook:=$DefaultPlaybook}"

  if [[ "$playbook" != *.* ]]
  then
    playbook="$playbook".yml
  fi

  if ! [[ -f "$playbooks"/"$playbook" ]]
  then
    printf 'The playbook %s/%s does not exist\n' "$playbooks" "$playbook" >&2
    return 1
  fi

  printf '%s' "$playbook"
}


resolve_playbook_dir()
{
  local playbooks="$1"

  if ! [[ "$playbooks" =~ ^/ ]]
  then
    playbooks="$(pwd)"/"$playbooks"
  fi

  if ! [[ -d "$playbooks" ]]
  then
    printf '%s is not a directory\n' "$playbooks" >&2
    return 1
  fi

  printf '%s' "$playbooks"
}


main "$@"
