FROM test-env-base:centos7

RUN yum install --assumeyes epel-release
RUN rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
RUN yum install --assumeyes jq python-pip

COPY ies/scripts/prep-svc-script.sh /tmp/prep-svc-script
COPY ies/scripts/service.sh.template /tmp/

ARG DBMS_HOST=dbms
ARG DBMS_PORT=5432
ARG DOMAIN=dstesting_default
ARG IRODS_SSL_CERTIFICATE_CHAIN_FILE=/etc/pki/tls/certs/server-chain.crt
ARG IRODS_SSL_CERTIFICATE_KEY_FILE=/etc/pki/tls/private/server.key
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods

COPY .tls/private/$DOMAIN.key $IRODS_SSL_CERTIFICATE_KEY_FILE
COPY .tls/certs/"$DOMAIN"-chain.crt $IRODS_SSL_CERTIFICATE_CHAIN_FILE

RUN /tmp/prep-svc-script

CMD [ "/service.sh" ]
