FROM test-env-base:centos7

RUN yum install --assumeyes epel-release
RUN rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
RUN yum install --assumeyes jq python-pip

COPY .default.key /etc/pki/tls/private/server.key
COPY .default.crt /etc/pki/tls/certs/server-chain.crt
COPY .ca.pem /etc/pki/tls/certs/irods-ca-bundle.pem
COPY ies/scripts/prep-svc-script.sh /tmp/prep-svc-script
COPY ies/scripts/service.sh.template /tmp/

ARG DBMS_HOST=dbms
ARG DBMS_PORT=5432
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_PASSWORD=rods

RUN /tmp/prep-svc-script

CMD [ "/service.sh" ]
