FROM test-env-base:centos6

RUN yum --assumeyes install epel-release
RUN rpm --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
RUN yum --assumeyes install jq

COPY rs/scripts/prep-svc-script.sh /tmp/prep-svc-script
COPY rs/scripts/service.sh.template /tmp/

ARG IRODS_CONTROL_PLANE_KEY=TEMPORARY__32byte_ctrl_plane_key
ARG IRODS_CONTROL_PLANE_PORT=1248
ARG IRODS_DEFAULT_RESOURCE=demoResc
ARG IRODS_DEFAULT_VAULT=/var/lib/irods/Vault
ARG IRODS_FIRST_EPHEMERAL_PORT=20000
ARG IRODS_HOST=rs
ARG IRODS_IES=ies
ARG IRODS_LAST_EPHEMERAL_PORT=20199
ARG IRODS_NEGOTIATION_KEY=TEMPORARY_32byte_negotiation_key
ARG IRODS_SCHEMA_VALIDATION=https://schemas.irods.org/configuration
ARG IRODS_SSL_CERTIFICATE_CHAIN_FILE=/etc/pki/tls/certs/server-chain.crt
ARG IRODS_SSL_CERTIFICATE_KEY_FILE=/etc/pki/tls/private/server.key
ARG IRODS_SSL_DH_PARAMS_FILE=/var/lib/irods/.irods/dhparams.pem
ARG IRODS_SYSTEM_GROUP=irods
ARG IRODS_SYSTEM_USER=irods
ARG IRODS_ZONE_KEY=TEMPORARY_zone_key
ARG IRODS_ZONE_NAME=tempZone
ARG IRODS_ZONE_PASSWORD=rods
ARG IRODS_ZONE_PORT=1247
ARG IRODS_ZONE_USER=rods

COPY .tls/custom.key $IRODS_SSL_CERTIFICATE_KEY_FILE
COPY .tls/custom-chain.crt $IRODS_SSL_CERTIFICATE_CHAIN_FILE

RUN yum --assumeyes install \
      openssl python-pip python-requests python-virtualenv which \
      https://files.renci.org/pub/irods/releases/4.1.10/centos6/irods-resource-4.1.10-centos6-x86_64.rpm

COPY rs/scripts/config-irods.sh /tmp/config-irods

RUN /tmp/config-irods
RUN /tmp/prep-svc-script

CMD [ "/service.sh" ]
