---
- name: configure iRODS
  hosts: irods
  become: true
  roles:
    - role: cyverse.cyverse-irods-cfg
      irods_icat_host: "{{ groups['ies'][0] }}"
      irods_default_resource_name: "{{ default_resource }}"
      irods_negotiation_key: "{{ negotiation_key }}"
      irods_server_control_plane_key: "{{ server_control_plane_key }}"
      irods_server_port_range_start: "{{ server_port_range_start }}"
      irods_server_port_range_end: "{{ server_port_range_end }}"
      irods_zone_key: "{{ zone_key }}"
      irods_zone_user: "{{ zone_admin_username }}"
      irods_amqp_uri: "{{ rabbitmq_broker_uri }}"
      irods_amqp_ephemeral: "{{ rabbitmq_ephemeral }}"
      irods_single_threaded_resources: "{{ single_threaded_resources }}"
      irods_db:
        host: "{{ groups['dbms'][0] }}"
        port: "{{ dbms_port }}"
        username: "{{ dbms_username }}"
        password: "{{ dbms_password }}"

- name: reload config files
  hosts: ies
  become: true
  become_user: irods
  gather_facts: false
  tasks:
    - file:
        path: /etc/irods/core.re
        state: touch
