---
- name: install dmidecode required by ansible gather_facts
  hosts: all:!unmanaged_systems:!localhost
  become: true
  gather_facts: false
  tasks:
    - name: install dmidecode support
      package:
        name: dmidecode
        state: present
        use: "{{ _package_manager }}"


- name: install required packages for ansible
  hosts: all:!unmanaged_systems:!localhost
  become: true
  tasks:
    - name: install EPEL repository on CentOS machines
      when: ansible_distribution == 'CentOS'
      package:
        name: epel-release
        state: present

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - jq
        - openssl
        - "{{ 'python2-pip' if ansible_distribution == 'CentOS'
                            and ansible_distribution_version is version ('7', '>=') else
              'python-pip' }}"
        - python-requests
        - python-virtualenv

    - name: install python-apt on Debian machines
      when: ansible_distribution == 'Debian'
      package:
        name: python-apt
        state: present
