---
# TODO implement
# - name: open firewall for iRODS

- name: setup iRODS service account
  hosts: irods:!unmanaged_systems
  become: true
  tasks:
    - name: create service group
      group:
        name: "{{ irods_service_group_name }}"
        system: yes

    - name: create service account
      user:
        name: "{{ irods_service_account_name }}"
        system: yes
        home: /var/lib/irods
        createhome: yes
        group: "{{ irods_service_group_name }}"
        comment: iRODS service

- include: mk_vaults.yml
- include: install_resource_pkg.yml
