---
- name: provision for iRODS
  hosts: irods:!unmanaged_systems
  become: true
  tasks:
    - name: install which
      package:
        name: which
        state: present

    - name: install uuidd
      package:
        name: uuidd
        state: present

    - name: create service group
      group:
        name: "{{ _irods_service_group_name }}"
        system: yes

    - name: create service account
      user:
        name: "{{ _irods_service_account_name }}"
        system: yes
        home: /var/lib/irods
        createhome: yes
        group: "{{ _irods_service_group_name }}"
        comment: iRODS Administrator

    - name: install TLS key
      when: _tls_key != ''
      copy:
        content: "{{ _tls_key }}"
        dest: "{{ _irods_ssl_certificate_key_file }}"

    - name: install TLS certificate chain
      when: _tls_cert != ''
      copy:
        content: "{{_tls_cert }}{{ _tls_intermediate_certs }}"
        dest: "{{ _irods_ssl_certificate_chain_file }}"


- name: provision additional for IES
  hosts: ies
  become: true
  gather_facts: false
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: present

    - name: configure linux kernel
      sysctl:
        name: kernel.{{ item.name }}
        value: "{{ item.value }}"
      with_items: "{{ _sysctl_kernel }}"
      tags:
        - no_testing


- import_playbook: update_hosts.yml


- import_playbook: firewall.yml
