#! /bin/bash
#
# This script deletes the ansible-tester image.


main()
{
  local execName
  execName=$(readlink --canonicalize "$0")

  local baseDir
  baseDir=$(dirname "$execName")

  if [ -n "$(docker images --filter reference=ansible-tester | tail --lines +2)" ]
  then
    docker rmi ansible-tester
  fi

  rm --force --recursive "$baseDir"/.tls
}


main "$@"
