---
webdav_cache_dir: /cache_vol
webdav_cache_max_file_size: 500000
webdav_cache_size: 500

webdav_tls_key_file: /etc/pki/tls/private/dstesting_default.key
webdav_tls_cert_file: /etc/pki/tls/certs/dstesting_default.crt
webdav_tls_chain_file: /etc/pki/tls/certs/ca.crt
