#! /bin/bash
#
# Usage:
#  clean INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Deletes the four docker images.

set -o errexit -o nounset -o pipefail


resolve_exec()
{
  local exe="$0"

  if [[ "$OSTYPE" == "darwin"* ]]
  then
    greadlink -f "$exe"
  else
    readlink --canonicalize "$exe"
  fi
}


main()
{
  local cfg="$*"

  local execName
  execName=$(resolve_exec "$0")

  local baseDir
  baseDir=$(dirname "$execName")

  if [[ -z "$cfg" ]]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]
  then
    cfg="$(pwd)"/"$cfg"
  fi

  # shellcheck disable=SC1090
  . "$cfg"

  local repository rest
  while read -r repository rest
  do
    docker rmi "$repository"
  done < <(docker images --filter reference="$ENV_NAME"_* | tail --lines +2)

  rm --force --recursive "$baseDir"/.tls
}


main "$*"
