---
version: "2.0"

services:
  amqp:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile

  dbms:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        IRODS_RESOURCES: "$IRODS_RS6_NAME:$IRODS_RS6_HOST:$IRODS_VAULT $IRODS_RS7_NAME:$IRODS_RS7_HOST:$IRODS_VAULT"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    tty: true

  ies:
    build:
      context: .
      dockerfile: ies/Dockerfile.configured
      args:
        DBMS_HOST: "$DBMS_HOST"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_HOST: "$IRODS_IES_HOST"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SSL_CA_CERTIFICATE_FILE: "$IRODS_SSL_CA_CERTIFICATE_FILE"
        IRODS_SSL_CERTIFICATE_CHAIN_FILE: "$IRODS_IES_TLS_CERT_CHAIN"
        IRODS_SSL_CERTIFICATE_KEY_FILE: "$IRODS_IES_TLS_KEY"
        IRODS_SSL_DH_PARAMS_FILE: "$IRODS_SSL_DH_PARAMS_FILE"
        IRODS_SYSTEM_GROUP: "$IRODS_IES_SYSTEM_GROUP"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    hostname: "$IRODS_IES_HOST"
    tty: true
    depends_on:
      - amqp
      - dbms

  ies_unconf:
    build:
      context: .
      dockerfile: ies/Dockerfile.unconfigured
      args:
        DBMS_HOST: "$DBMS_HOST"
        IRODS_SSL_CA_CERTIFICATE_FILE: "$IRODS_SSL_CA_CERTIFICATE_FILE"
        IRODS_SSL_CERTIFICATE_CHAIN_FILE: "$IRODS_IES_TLS_CERT_CHAIN"
        IRODS_SSL_CERTIFICATE_KEY_FILE: "$IRODS_IES_TLS_KEY"
        IRODS_SYSTEM_GROUP: "$IRODS_IES_SYSTEM_GROUP"
    hostname: "$IRODS_IES_UNCONF_HOST"
    tty: true

  load_balancer:
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    depends_on:
      - apache
      - ies

  rs_centos6:
    build:
      context: .
      dockerfile: rs/Dockerfile.centos6
      args:
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_DEFAULT_VAULT: "$IRODS_VAULT"
        IRODS_HOST: "$IRODS_RS6_HOST"
        IRODS_IES: "$IRODS_IES_HOST"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SSL_CA_CERTIFICATE_FILE: "$IRODS_SSL_CA_CERTIFICATE_FILE"
        IRODS_SSL_CERTIFICATE_CHAIN_FILE: "$IRODS_RS_TLS_CERT_CHAIN"
        IRODS_SSL_CERTIFICATE_KEY_FILE: "$IRODS_RS_TLS_KEY"
        IRODS_SSL_DH_PARAMS_FILE: "$IRODS_SSL_DH_PARAMS_FILE"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    cap_add:
      - NET_ADMIN
    hostname: "$IRODS_RS6_HOST"
    tty: true
    depends_on:
      - ies

  rs_centos7:
    build:
      context: .
      dockerfile: rs/Dockerfile.centos7
      args:
        IRODS_IES: "$IRODS_IES_HOST"
        IRODS_SSL_CA_CERTIFICATE_FILE: "$IRODS_SSL_CA_CERTIFICATE_FILE"
        IRODS_SSL_CERTIFICATE_CHAIN_FILE: "$IRODS_RS_TLS_CERT_CHAIN"
        IRODS_SSL_CERTIFICATE_KEY_FILE: "$IRODS_RS_TLS_KEY"
    hostname: "$IRODS_RS7_HOST"
    tty: true
